// Read name/version/license from installed packages (facts, not guesses).
// Output committed as src/data/credits.generated.ts. Re-run after dep changes.
import { readFileSync, writeFileSync, existsSync } from "node:fs";
import { join, dirname } from "node:path";
import { fileURLToPath } from "node:url";

const root = join(dirname(fileURLToPath(import.meta.url)), "..");
const direct = Object.keys(
  JSON.parse(readFileSync(join(root, "package.json"), "utf8")).dependencies ?? {}
);

const rows = [];
for (const name of direct.sort()) {
  const pkgPath = join(root, "node_modules", name, "package.json");
  if (!existsSync(pkgPath)) {
    console.error(`[credits] missing node_modules/${name}, run pnpm install first`);
    process.exit(1);
  }
  const pkg = JSON.parse(readFileSync(pkgPath, "utf8"));
  rows.push({ name: pkg.name, version: pkg.version, license: pkg.license ?? "xem gói" });
}

const ts = `// AUTO-GENERATED by scripts/generate-credits.mjs — do not edit by hand.
export interface CreditRow { name: string; version: string; license: string; }
export const CREDITS: CreditRow[] = ${JSON.stringify(rows, null, 2)};
`;
writeFileSync(join(root, "src", "data", "credits.generated.ts"), ts);
console.log(`[credits] wrote ${rows.length} rows.`);
for (const r of rows) console.log(`  ${r.name}@${r.version} (${r.license})`);
