// AUTO-GENERATED by scripts/generate-credits.mjs — do not edit by hand.
export interface CreditRow { name: string; version: string; license: string; }
export const CREDITS: CreditRow[] = [
  {
    "name": "dexie",
    "version": "4.4.6",
    "license": "Apache-2.0"
  },
  {
    "name": "katex",
    "version": "0.19.0",
    "license": "MIT"
  },
  {
    "name": "next",
    "version": "16.3.8",
    "license": "MIT"
  },
  {
    "name": "react",
    "version": "19.2.8",
    "license": "MIT"
  },
  {
    "name": "react-dom",
    "version": "19.2.8",
    "license": "MIT"
  },
  {
    "name": "react-markdown",
    "version": "10.1.0",
    "license": "MIT"
  },
  {
    "name": "rehype-katex",
    "version": "7.0.1",
    "license": "MIT"
  },
  {
    "name": "remark-math",
    "version": "6.0.0",
    "license": "MIT"
  },
  {
    "name": "ts-fsrs",
    "version": "5.4.2",
    "license": "MIT"
  },
  {
    "name": "yaml",
    "version": "2.9.1",
    "license": "ISC"
  },
  {
    "name": "zod",
    "version": "4.6.5",
    "license": "MIT"
  },
  {
    "name": "zustand",
    "version": "5.0.15",
    "license": "MIT"
  }
];
