import Dexie, { type Table } from "dexie";

export interface BookmarkRow {
  questionId: string;
  topicId: string;
  createdAt: number;
}

export interface NoteRow {
  questionId: string;
  text: string;
  updatedAt: number;
}

export interface PracticeEventRow {
  /** UUID v4 generated by the client (append-only, idempotent upsert). */
  id: string;
  questionId: string;
  topicId: string;
  level: string;
  qtype: string;
  correct: boolean;
  /** Correct statements (mcq 0/1, tf4 0-4). Old rows may lack it. */
  correctCount?: number;
  durationMs: number;
  createdAt: number;
}

export interface ReportRow {
  id: string;
  questionId: string;
  questionVersion: number;
  category: string;
  detail: string;
  createdAt: number;
}

export interface SrsStateRow {
  cardId: string;
  due: string;
  stability: number;
  difficulty: number;
  scheduledDays: number;
  reps: number;
  lapses: number;
  state: number;
  updatedAt: number;
}

export interface ExamSessionRow {
  id: string;
  seed: number;
  mode: "paper" | "computer";
  full: boolean;
  questions: import("@/domain/question-schema").Question[];
  answers: import("@/domain/scoring").ExamAnswers;
  flags: string[];
  durationsMs: Record<string, number>;
  startedAt: number;
  endsAt: number;
  submittedAt: number | null;
  autoSubmitted: boolean;
  /** Owning tab for the multi-tab guard; refreshed by heartbeat. */
  tabId: string;
  updatedAt: number;
}

class CncnDb extends Dexie {
  bookmarks!: Table<BookmarkRow, string>;
  notes!: Table<NoteRow, string>;
  practiceEvents!: Table<PracticeEventRow, string>;
  reports!: Table<ReportRow, string>;
  examSessions!: Table<ExamSessionRow, string>;
  srsStates!: Table<SrsStateRow, string>;

  constructor() {
    super("cncn");
    // v1 (M3): practice persistence. Future stores go in version(2) with
    // explicit upgrade() to migrate — never redefine version(1).
    this.version(1).stores({
      bookmarks: "questionId, topicId, createdAt",
      notes: "questionId, updatedAt",
      practiceEvents: "id, questionId, topicId, createdAt",
      reports: "id, questionId, createdAt",
    });
    // v2 (M4): exam sessions. New empty store; v1 data untouched.
    this.version(2).stores({
      examSessions: "id, updatedAt",
    });
    // v3 (M5): SRS card states. New empty store; older data untouched.
    this.version(3).stores({
      srsStates: "cardId, due",
    });
    // v4 (M6): practiceEvents gains correctCount (non-indexed, no backfill;
    // old rows fall back to all-or-nothing).
    this.version(4).stores({
      bookmarks: "questionId, topicId, createdAt",
      notes: "questionId, updatedAt",
      practiceEvents: "id, questionId, topicId, createdAt",
      reports: "id, questionId, createdAt",
      examSessions: "id, updatedAt",
      srsStates: "cardId, due",
    });
  }
}

let instance: CncnDb | null = null;

/** Lazy singleton. Only call from client components (IndexedDB needs a browser). */
export function getDb(): CncnDb {
  if (!instance) instance = new CncnDb();
  return instance;
}

export function newId(): string {
  return crypto.randomUUID();
}
